messageCode: device-does-not-exist-in-the-plard-environment
messageDomain: cadastral-core
summary: device-does-not-exist-in-the-plard-environment
type: error
languages:
- code: pt-BR
  message: dispositivo não existe no ambiente PLARD.
- code: en-US
  message: device does not exist in the plard environment.
- code: es-ES
  message: El dispositivo no existe en el entorno plard.
- code: es-CL
  message: dispositivo não existe no ambiente PLARD.