messageCode: productcode-is-required
messageDomain: cadastral-core
summary: productcode-is-required
type: error
languages:
- code: pt-BR
  message: Código do produto é obrigatório.
- code: en-US
  message: Productcode is required.
- code: es-ES
  message: Se requiere codigo de producto.
- code: es-CL
  message: Se requiere codigo de producto.
